server:
  port: 7000
spring:
  cloud:
    nacos:
      discovery:
        server-addr: @nacos.server-addr@
        namespace: @nacos.namespace@
        username: @nacos.username@
        password: @nacos.password@
    gateway:
      routes:
        - id: consumer
          uri: lb://spring-cloud-consumer
          predicates:
            - Path=/api/v1/**
          filters:
            - StripPrefix=0
      discovery:
        locator:
          enabled: true
